// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY2tzBSRZV7x5httgbW_u5s20_9h-m0wE',
    appId: '1:258479137101:web:bd681d59e50af90e139704',
    messagingSenderId: '258479137101',
    projectId: 'chattappflutter-4d577',
    authDomain: 'chattappflutter-4d577.firebaseapp.com',
    storageBucket: 'chattappflutter-4d577.appspot.com',
    measurementId: 'G-HH7Z32Q9YX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoXmx5NxPWddeXDFrGzfsr33g2CekPALk',
    appId: '1:258479137101:android:f23822af43c093ce139704',
    messagingSenderId: '258479137101',
    projectId: 'chattappflutter-4d577',
    storageBucket: 'chattappflutter-4d577.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1nlX5bHxDvGddwIGsk_7M9mhdptigph8',
    appId: '1:258479137101:ios:34da591588a3212c139704',
    messagingSenderId: '258479137101',
    projectId: 'chattappflutter-4d577',
    storageBucket: 'chattappflutter-4d577.appspot.com',
    iosClientId: '258479137101-m9f3mqi10son7mdm3i2id61mc1i0uu56.apps.googleusercontent.com',
    iosBundleId: 'com.diginerds.chatAppFlutter',
  );
}
